id: A7217CD6F
title: 'The Liberating Guide: A Prayer to Gyalwa Yangönpa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:30:03.362852
  last_modified_at: 2022-02-28 23:30:03.362859
